name: Deploy Backend to Cloud

on:
  push:
    branches: [ main ]
    paths: ['backend/**']
  workflow_dispatch:

jobs:
  deploy-render:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to Render
      uses: render-oss/render-deploy-action@v1.4.4
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
    
    - name: Notify deployment status
      run: |
        echo "✅ Backend deployed to Render"
        echo "🔗 API URL: https://amrikyy-ai-backend.onrender.com"

  deploy-railway:
    runs-on: ubuntu-latest
    if: false  # Disabled by default, enable by changing to true
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to Railway
      uses: railway-oss/railway-deploy@v1
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: backend
    
    - name: Notify Railway deployment
      run: |
        echo "✅ Backend deployed to Railway"

  test-endpoints:
    needs: deploy-render
    runs-on: ubuntu-latest
    steps:
    - name: Test health endpoint
      run: |
        curl -f https://amrikyy-ai-backend.onrender.com/health || echo "❌ Health check failed"
        
    - name: Test API documentation
      run: |
        curl -f https://amrikyy-ai-backend.onrender.com/api/v1/docs || echo "❌ API docs unavailable"
